#!/bin/bash
cp /home/berk/.gradle/caches/modules-2/files-2.1/javax.ws.rs/javax.ws.rs-api/2.0.1/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.jersey.core/jersey-server/2.22.2/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.jersey.core/jersey-client/2.22.2/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.jersey.core/jersey-common/2.22.2/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.jersey.containers/jersey-container-grizzly2-http/2.22.2/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.jersey.media/jersey-media-jaxb/2.22.2/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/javax.annotation/javax.annotation-api/1.2/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.hk2/hk2-api/2.4.0-b34/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.hk2.external/javax.inject/2.4.0-b34/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.hk2/hk2-locator/2.4.0-b34/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.jersey.bundles.repackaged/jersey-guava/2.22.2/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.hk2/osgi-resource-locator/1.0.1/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.grizzly/grizzly-http-server/2.3.23/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.hk2/hk2-utils/2.4.0-b34/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.hk2.external/aopalliance-repackaged/2.4.0-b34/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.javassist/javassist/3.18.1-GA/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.grizzly/grizzly-http/2.3.23/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.grizzly/grizzly-framework/2.3.23/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.jersey.media/jersey-media-json-jackson/2.22.2/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.glassfish.jersey.ext/jersey-entity-filtering/2.22.2/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.jaxrs/jackson-jaxrs-base/2.5.4/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.jaxrs/jackson-jaxrs-json-provider/2.5.4/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.5.4/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.5.4/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.5.4/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-jaxb-annotations/2.5.4/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/io.reactivex/rxjava/1.1.3/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.reactivestreams/reactive-streams/1.0.0/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.springframework/spring-context/4.2.5.RELEASE/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/4.2.5.RELEASE/*/*.jar libs/
cp /home/berk/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/*/*.jar libs/
